wandb_version: 1

learning_rate:
  desc: null
  value: 0.002
architecture:
  desc: null
  value: Adversarial
dataset:
  desc: null
  value: Art generation from kaggle
Epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692177083.244512
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 4
      - 5
